
export const images = [
    { thumb: require("../images/_thumbnails/00.jpg").default, full: require("../images/_resized/00.jpg").default, text: require("../contents/00.html").default, nome: "Presentazione", cognome: "" },
    { thumb: require("../images/_thumbnails/01.jpg").default, full: require("../images/_resized/01.jpg").default, text: require("../contents/01.html").default, nome: "Sabatino", cognome: "Lopez" },
    { thumb: require("../images/_thumbnails/02.jpg").default, full: require("../images/_resized/02.jpg").default, text: require("../contents/02.html").default, nome: "B.", cognome: "G." },
    { thumb: require("../images/_thumbnails/03.jpg").default, full: require("../images/_resized/03.jpg").default, text: require("../contents/03.html").default, nome: "Anton Giulio", cognome: "Barilli" },
    { thumb: require("../images/_thumbnails/04.jpg").default, full: require("../images/_resized/04.jpg").default, text: require("../contents/04.html").default, nome: "Sev.", cognome: "Ferrari" },
    { thumb: require("../images/_thumbnails/05.jpg").default, full: require("../images/_resized/05.jpg").default, text: require("../contents/05.html").default, nome: "G.", cognome: "Bolima" },
    { thumb: require("../images/_thumbnails/06.jpg").default, full: require("../images/_resized/06.jpg").default, text: require("../contents/06.html").default, nome: "Angelo", cognome: "Tomaselli" },
    { thumb: require("../images/_thumbnails/07.jpg").default, full: require("../images/_resized/07.jpg").default, text: require("../contents/07.html").default, nome: "Dino", cognome: "Mantovani" },
    { thumb: require("../images/_thumbnails/08.jpg").default, full: require("../images/_resized/08.jpg").default, text: require("../contents/08.html").default, nome: "Giovanni", cognome: "Duprè" },
    { thumb: require("../images/_thumbnails/09.jpg").default, full: require("../images/_resized/09.jpg").default, text: require("../contents/09.html").default, nome: "Giannino", cognome: "Antona Traversi" },
    { thumb: require("../images/_thumbnails/10.jpg").default, full: require("../images/_resized/10.jpg").default, text: require("../contents/10.html").default, nome: "Giovanni", cognome: "Marradi" },
    { thumb: require("../images/_thumbnails/11.jpg").default, full: require("../images/_resized/11.jpg").default, text: require("../contents/11.html").default, nome: "Marco", cognome: "Praga" },
    { thumb: require("../images/_thumbnails/12.jpg").default, full: require("../images/_resized/12.jpg").default, text: require("../contents/12.html").default, nome: "Mascagni", cognome: "Mascagni" },
    { thumb: require("../images/_thumbnails/13.jpg").default, full: require("../images/_resized/13.jpg").default, text: require("../contents/13.html").default, nome: "Bracco", cognome: "Bracco" },
    { thumb: require("../images/_thumbnails/14.jpg").default, full: require("../images/_resized/14.jpg").default, text: require("../contents/14.html").default, nome: "Cantagalli", cognome: "Cantagalli" },
    { thumb: require("../images/_thumbnails/15.jpg").default, full: require("../images/_resized/15.jpg").default, text: require("../contents/15.html").default, nome: "Novelli", cognome: "Novelli" },
    { thumb: require("../images/_thumbnails/16.jpg").default, full: require("../images/_resized/16.jpg").default, text: require("../contents/16.html").default, nome: "Irma Gramatica", cognome: "Irma Gramatica" },
    { thumb: require("../images/_thumbnails/17.jpg").default, full: require("../images/_resized/17.jpg").default, text: require("../contents/17.html").default, nome: "Mariani", cognome: "Mariani" },
    { thumb: require("../images/_thumbnails/18.jpg").default, full: require("../images/_resized/18.jpg").default, text: require("../contents/18.html").default, nome: "Pilotta", cognome: "Pilotta" },
    { thumb: require("../images/_thumbnails/19.jpg").default, full: require("../images/_resized/19.jpg").default, text: require("../contents/19.html").default, nome: "Zago", cognome: "Zago" },
    { thumb: require("../images/_thumbnails/20.jpg").default, full: require("../images/_resized/20.jpg").default, text: require("../contents/20.html").default, nome: "Emanuel", cognome: "Emanuel" },
    { thumb: require("../images/_thumbnails/21.jpg").default, full: require("../images/_resized/21.jpg").default, text: require("../contents/21.html").default, nome: "Ferravilla", cognome: "Ferravilla" },
    { thumb: require("../images/_thumbnails/22.jpg").default, full: require("../images/_resized/22.jpg").default, text: require("../contents/22.html").default, nome: "Pascoli", cognome: "Pascoli" },
    { thumb: require("../images/_thumbnails/23.jpg").default, full: require("../images/_resized/23.jpg").default, text: require("../contents/23.html").default, nome: "Picciola", cognome: "Picciola" },
    { thumb: require("../images/_thumbnails/24.jpg").default, full: require("../images/_resized/24.jpg").default, text: require("../contents/24.html").default, nome: "Cesareo", cognome: "Cesareo" },
    { thumb: require("../images/_thumbnails/25.jpg").default, full: require("../images/_resized/25.jpg").default, text: require("../contents/25.html").default, nome: "Boner", cognome: "Boner" },
    { thumb: require("../images/_thumbnails/26.jpg").default, full: require("../images/_resized/26.jpg").default, text: require("../contents/26.html").default, nome: "Franchetti", cognome: "Franchetti" },
    { thumb: require("../images/_thumbnails/27.jpg").default, full: require("../images/_resized/27.jpg").default, text: require("../contents/27.html").default, nome: "Edo Calandra", cognome: "Edo Calandra" },
    { thumb: require("../images/_thumbnails/28.jpg").default, full: require("../images/_resized/28.jpg").default, text: require("../contents/28.html").default, nome: "Mazzoni", cognome: "Mazzoni" },
    { thumb: require("../images/_thumbnails/29.jpg").default, full: require("../images/_resized/29.jpg").default, text: require("../contents/29.html").default, nome: "Capitelli", cognome: "Capitelli" },
    { thumb: require("../images/_thumbnails/30.jpg").default, full: require("../images/_resized/30.jpg").default, text: require("../contents/30.html").default, nome: "deRoberto", cognome: "deRoberto" },
    { thumb: require("../images/_thumbnails/31.jpg").default, full: require("../images/_resized/31.jpg").default, text: require("../contents/31.html").default, nome: "DeLollis", cognome: "DeLollis" },
    { thumb: require("../images/_thumbnails/32.jpg").default, full: require("../images/_resized/32.jpg").default, text: require("../contents/32.html").default, nome: "Butti", cognome: "Butti" },
    { thumb: require("../images/_thumbnails/33.jpg").default, full: require("../images/_resized/33.jpg").default, text: require("../contents/33.html").default, nome: "Anastasi", cognome: "Anastasi" },
    { thumb: require("../images/_thumbnails/34.jpg").default, full: require("../images/_resized/34.jpg").default, text: require("../contents/34.html").default, nome: "Vassallo", cognome: "Vassallo" },
    { thumb: require("../images/_thumbnails/35.jpg").default, full: require("../images/_resized/35.jpg").default, text: require("../contents/35.html").default, nome: "Sodini", cognome: "Sodini" },
    { thumb: require("../images/_thumbnails/36.jpg").default, full: require("../images/_resized/36.jpg").default, text: require("../contents/36.html").default, nome: "deLuca", cognome: "deLuca" },
    { thumb: require("../images/_thumbnails/37.jpg").default, full: require("../images/_resized/37.jpg").default, text: require("../contents/37.html").default, nome: "Puccini", cognome: "Puccini" },
    { thumb: require("../images/_thumbnails/38.jpg").default, full: require("../images/_resized/38.jpg").default, text: require("../contents/38.html").default, nome: "Vigliardi", cognome: "Vigliardi" },
    { thumb: require("../images/_thumbnails/39.jpg").default, full: require("../images/_resized/39.jpg").default, text: require("../contents/39.html").default, nome: "Chiarini", cognome: "Chiarini" },
    { thumb: require("../images/_thumbnails/40.jpg").default, full: require("../images/_resized/40.jpg").default, text: require("../contents/40.html").default, nome: "Davide Calandra", cognome: "Davide Calandra" },
    { thumb: require("../images/_thumbnails/41.jpg").default, full: require("../images/_resized/41.jpg").default, text: require("../contents/41.html").default, nome: "Carducci", cognome: "Carducci" },
    { thumb: require("../images/_thumbnails/42.jpg").default, full: require("../images/_resized/42.jpg").default, text: require("../contents/42.html").default, nome: "Giacosa", cognome: "Giacosa" },
    { thumb: require("../images/_thumbnails/43.jpg").default, full: require("../images/_resized/43.jpg").default, text: require("../contents/43.html").default, nome: "Verga", cognome: "Verga" },
    { thumb: require("../images/_thumbnails/44.jpg").default, full: require("../images/_resized/44.jpg").default, text: require("../contents/44.html").default, nome: "Ximenes", cognome: "Ximenes" },
    { thumb: require("../images/_thumbnails/45.jpg").default, full: require("../images/_resized/45.jpg").default, text: require("../contents/45.html").default, nome: "Trilussa", cognome: "Trilussa" },
    { thumb: require("../images/_thumbnails/46.jpg").default, full: require("../images/_resized/46.jpg").default, text: require("../contents/46.html").default, nome: "Pascarella", cognome: "Pascarella" },
    { thumb: require("../images/_thumbnails/47.jpg").default, full: require("../images/_resized/47.jpg").default, text: require("../contents/47.html").default, nome: "Duse", cognome: "Duse" },
    { thumb: require("../images/_thumbnails/48.jpg").default, full: require("../images/_resized/48.jpg").default, text: require("../contents/48.html").default, nome: "Zacconi", cognome: "Zacconi" },
    { thumb: require("../images/_thumbnails/49.jpg").default, full: require("../images/_resized/49.jpg").default, text: require("../contents/49.html").default, nome: "Giordano", cognome: "Giordano" },
    { thumb: require("../images/_thumbnails/50.jpg").default, full: require("../images/_resized/50.jpg").default, text: require("../contents/50.html").default, nome: "Aldi", cognome: "Aldi" },
    { thumb: require("../images/_thumbnails/51.jpg").default, full: require("../images/_resized/51.jpg").default, text: require("../contents/51.html").default, nome: "Rovetta", cognome: "Rovetta" },
    { thumb: require("../images/_thumbnails/52.jpg").default, full: require("../images/_resized/52.jpg").default, text: require("../contents/52.html").default, nome: "Della Quercia", cognome: "Della Quercia" },
    { thumb: require("../images/_thumbnails/53.jpg").default, full: require("../images/_resized/53.jpg").default, text: require("../contents/53.html").default, nome: "Dal Bono", cognome: "Dal Bono" },
    { thumb: require("../images/_thumbnails/54.jpg").default, full: require("../images/_resized/54.jpg").default, text: require("../contents/54.html").default, nome: "Simoni", cognome: "Simoni" },
    { thumb: require("../images/_thumbnails/55.jpg").default, full: require("../images/_resized/55.jpg").default, text: require("../contents/55.html").default, nome: "Moretti", cognome: "Moretti" },
    { thumb: require("../images/_thumbnails/56.jpg").default, full: require("../images/_resized/56.jpg").default, text: require("../contents/56.html").default, nome: "Pascucci", cognome: "Pascucci" },
    { thumb: require("../images/_thumbnails/57.jpg").default, full: require("../images/_resized/57.jpg").default, text: require("../contents/57.html").default, nome: "Emma Gramatica", cognome: "Emma Gramatica" },
    { thumb: require("../images/_thumbnails/58.jpg").default, full: require("../images/_resized/58.jpg").default, text: require("../contents/58.html").default, nome: "Varaldo", cognome: "Varaldo" },
    { thumb: require("../images/_thumbnails/59.jpg").default, full: require("../images/_resized/59.jpg").default, text: require("../contents/59.html").default, nome: "Borgese", cognome: "Borgese" },
    { thumb: require("../images/_thumbnails/60.jpg").default, full: require("../images/_resized/60.jpg").default, text: require("../contents/60.html").default, nome: "Martini", cognome: "Martini" },
    { thumb: require("../images/_thumbnails/61.jpg").default, full: require("../images/_resized/61.jpg").default, text: require("../contents/61.html").default, nome: "Cascella", cognome: "Cascella" },
    { thumb: require("../images/_thumbnails/62.jpg").default, full: require("../images/_resized/62.jpg").default, text: require("../contents/62.html").default, nome: "Ruggi", cognome: "Ruggi" },
    { thumb: require("../images/_thumbnails/63.jpg").default, full: require("../images/_resized/63.jpg").default, text: require("../contents/63.html").default, nome: "Deledda", cognome: "Deledda" },
    { thumb: require("../images/_thumbnails/64.jpg").default, full: require("../images/_resized/64.jpg").default, text: require("../contents/64.html").default, nome: "Panzini", cognome: "Panzini" },
    { thumb: require("../images/_thumbnails/65.jpg").default, full: require("../images/_resized/65.jpg").default, text: require("../contents/65.html").default, nome: "Dandolo", cognome: "Dandolo" }
];
